### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by fcakyon** [lucidrains/mlp-mixer-pytorch#1]
Do you plan to add any training script?

**Comment by lucidrains** [comment]
@fcakyon going to point you at Ross' excellent vision library for that :) https://github.com/rwightman/pytorch-image-models

**Comment by fcakyon** [comment]
didnt know [it was present there](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/mlp_mixer.py), thanks for pointing :)
