### ISSUE TITLE
expansion_factor on tokens is actually a bottleneck in original codebase

### ISSUE THREAD

**Issue by chazzmoney** [lucidrains/mlp-mixer-pytorch#11]
Thanks for your implementation. In comparing your codebase to [the author's implementation](https://github.com/google-research/vision_transformer/blob/main/vit_jax/models_mixer.py), I discovered that while you have a single expansion factor in your configuration, the authors have separate values - one for tokens and one for channels.

Specifically, [their channels expansion factor is 4, but their tokens expansion factor is 0.5](https://github.com/google-research/vision_transformer/blob/dc8ddbcdeefd281d6cc7fea0c97355495688ca9c/vit_jax/configs/models.py#L279-L280). (The hidden_dim is the base projection size). Note that they actually use a feature count, but I'm translating to the mechanism you use in this codebase.

Thus, when [executing the MixerBlock](https://github.com/google-research/vision_transformer/blob/main/vit_jax/models_mixer.py#L41-L45), the tokens "expansion" is actually a bottleneck.

The parameters can be verified as well in [Table 1 ("Specifications of Mixer Architectures") at the top of page 4 in version 4 (the current version as of Feb 14, 2022) of their paper](https://arxiv.org/pdf/2105.01601v4.pdf).

I'm not suggesting that anything necessarily needs to change in your implementation. However, if you wanted to align your codebase to be able to fully replicate the author's work, you may consider allowing for two separate parameters - token_expansion_factor and channels_expansion_factor.

Thank you again for this work, and for all your contributions generally. You are a an incredible asset to the community.

**Comment by lucidrains** [comment]
@chazzmoney Hi Charles! You are correct and I have made the change in 0.1.0! https://github.com/lucidrains/mlp-mixer-pytorch/releases/tag/0.1.0
