### ISSUE TITLE
Question about Parameters

### ISSUE THREAD

**Issue by Arvin-Wan** [lucidrains/mlp-mixer-pytorch#13]
Why are the parameters so different from the one in the paper?

Take the S-16 as an example: 
* your model : 5.01 M
*  Paper : 18 M

I compared your model with official imlementation model  ([Jax version](https://github.com/google-research/vision_transformer/blob/main/vit_jax/models_mixer.py)),  maybe you made a mistake.

I can not find any transpose operation in your model, which is necessary for Mixer layer. 

If i do not understand your model, please correct me ,thanks a lot!

![image](https://user-images.githubusercontent.com/63688684/233833554-a5a02901-07aa-4123-98fb-a5d1b5db068a.png)

**Comment by tinsir888** [comment]
> Why are the parameters so different from the one in the paper?
> 
> Take the S-16 as an example:
> 
>     * your model : 5.01 M
> 
>     * Paper : 18 M
> 
> 
> I compared your model with official imlementation model ([Jax version](https://github.com/google-research/vision_transformer/blob/main/vit_jax/models_mixer.py)), maybe you made a mistake.
> 
> I can not find any transpose operation in your model, which is necessary for Mixer layer.
> 
> If i do not understand your model, please correct me ,thanks a lot!
> 
> ![image](https://user-images.githubusercontent.com/63688684/233833554-a5a02901-07aa-4123-98fb-a5d1b5db068a.png)

It appears that the code implementation completely lacks the operation of matrix transposition, and you are correct.

**Comment by lucidrains** [comment]
it is taking advantage of the fact that conv module acts on the first dimension, and linear module acts on the last https://github.com/lucidrains/mlp-mixer-pytorch/blob/main/mlp_mixer_pytorch/mlp_mixer_pytorch.py#L30 this trick saves from needing a transpose

**Comment by tinsir888** [comment]
I really appreciate the author's explanation here, it makes it much easier for me to understand the code.
