### ISSUE TITLE
Dall-E implementation

### ISSUE THREAD

**Issue by robvanvolt** [lucidrains/mlp-mixer-pytorch#2]
Amazing work! How difficult is it to implement mlp into Dall-E? As the whole idea around Dall-E evolves around attention layers and transformers, I wonder if this simpler model would enable smaller, equally capable models...

**Comment by lucidrains** [comment]
@robvanvolt ohh hey Rob! I don't think this can be applied to DALL-E since autoregressive is a bit of a special case - i'll keep thinking though :)
