### ISSUE TITLE
Question: dynamic size?

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/mlp-mixer-pytorch#5]
Can this work with dynamic size?
From reading the paper, it doesn't look like that's possible.
Is that right?
If so, what a shame...

**Comment by lucidrains** [comment]
unfortunately not :(

**Comment by pfeatherstone** [comment]
This is something papers should put in big black letters. Some practically minded engineers might argue that inferring all your images at 224x224 isn't always a good idea.
